global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Uno.Extensions.Http.Kiota;
global using unoDynamicUI.Models;
global using unoDynamicUI.Models.DynamicForms;
global using unoDynamicUI.Presentation;
global using unoDynamicUI.Presentation.DynamicForms;
global using unoDynamicUI.Services.DynamicForms;
global using unoDynamicUI.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
